/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root.jsx'
import { Route as IndexImport } from './routes/index.jsx'
import { Route as TransactionsIndexImport } from './routes/transactions.index.jsx'
import { Route as SettingsIndexImport } from './routes/settings.index.jsx'
import { Route as RulesIndexImport } from './routes/rules.index.jsx'
import { Route as LoginIndexImport } from './routes/login.index.jsx'
import { Route as AccountsIndexImport } from './routes/accounts.index.jsx'
import { Route as RulesRuleIdImport } from './routes/rules.$ruleId.jsx'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
})

const TransactionsIndexRoute = TransactionsIndexImport.update({
  path: '/transactions/',
  getParentRoute: () => rootRoute,
})

const SettingsIndexRoute = SettingsIndexImport.update({
  path: '/settings/',
  getParentRoute: () => rootRoute,
})

const RulesIndexRoute = RulesIndexImport.update({
  path: '/rules/',
  getParentRoute: () => rootRoute,
})

const LoginIndexRoute = LoginIndexImport.update({
  path: '/login/',
  getParentRoute: () => rootRoute,
})

const AccountsIndexRoute = AccountsIndexImport.update({
  path: '/accounts/',
  getParentRoute: () => rootRoute,
})

const RulesRuleIdRoute = RulesRuleIdImport.update({
  path: '/rules/$ruleId',
  getParentRoute: () => rootRoute,
})

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  RulesRuleIdRoute,
  AccountsIndexRoute,
  LoginIndexRoute,
  RulesIndexRoute,
  SettingsIndexRoute,
  TransactionsIndexRoute,
])

/* prettier-ignore-end */
