/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root.jsx'
import { Route as IndexImport } from './routes/index.jsx'
import { Route as TransactionsIndexImport } from './routes/transactions.index.jsx'
import { Route as SettingsIndexImport } from './routes/settings.index.jsx'
import { Route as RulesIndexImport } from './routes/rules.index.jsx'
import { Route as LoginIndexImport } from './routes/login.index.jsx'
import { Route as AccountsIndexImport } from './routes/accounts.index.jsx'
import { Route as RulesRuleIdImport } from './routes/rules.$ruleId.jsx'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
})

const TransactionsIndexRoute = TransactionsIndexImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRoute,
})

const SettingsIndexRoute = SettingsIndexImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRoute,
})

const RulesIndexRoute = RulesIndexImport.update({
  id: '/rules/',
  path: '/rules/',
  getParentRoute: () => rootRoute,
})

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
})

const AccountsIndexRoute = AccountsIndexImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => rootRoute,
})

const RulesRuleIdRoute = RulesRuleIdImport.update({
  id: '/rules/$ruleId',
  path: '/rules/$ruleId',
  getParentRoute: () => rootRoute,
})

// Create and export the route tree

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  RulesRuleIdRoute: RulesRuleIdRoute,
  AccountsIndexRoute: AccountsIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  RulesIndexRoute: RulesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
}

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/rules/$ruleId",
        "/accounts/",
        "/login/",
        "/rules/",
        "/settings/",
        "/transactions/"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/rules/$ruleId": {
      "filePath": "rules.$ruleId.jsx"
    },
    "/accounts/": {
      "filePath": "accounts.index.jsx"
    },
    "/login/": {
      "filePath": "login.index.jsx"
    },
    "/rules/": {
      "filePath": "rules.index.jsx"
    },
    "/settings/": {
      "filePath": "settings.index.jsx"
    },
    "/transactions/": {
      "filePath": "transactions.index.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
