# Generated by Selenium IDE
import json
import time

import pytest
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait


class TestRest():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_rest(self):
    # Test name: rest
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://rest.com.au/")
    # 2 | setWindowSize | 1111x848 | 
    self.driver.set_window_size(1111, 848)
    # 3 | click | css=.btn--outlined > .icon-angle-down | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn--outlined > .icon-angle-down").click()
    # 4 | click | linkText=Member login | 
    self.driver.find_element(By.LINK_TEXT, "Member login").click()
    # 5 | type | css=input | pcollins1@gmail.com
    self.driver.find_element(By.CSS_SELECTOR, "input").send_keys("pcollins1@gmail.com")
    # 6 | click | css=input | 
    self.driver.find_element(By.CSS_SELECTOR, "input").click()
    # 7 | click | css=.rs-ga-tooltip | 
    self.driver.find_element(By.CSS_SELECTOR, ".rs-ga-tooltip").click()
    # 8 | click | css=.rs-ga-container | 
    self.driver.find_element(By.CSS_SELECTOR, ".rs-ga-container").click()
    # 9 | click | css=.rs-ga-button-primary | 
    self.driver.find_element(By.CSS_SELECTOR, ".rs-ga-button-primary").click()
    # 10 | type | css=input | 6PamzZU9wkGebstP
    self.driver.find_element(By.CSS_SELECTOR, "input").send_keys("<PASS>")
    # 11 | close |  | 
    self.driver.close()
  
